// import './js_2/get_in_touch_with_us';
import './js/scroll';
import './js/anchor-scroll';
import { galleryMarkup } from './js/create-our-cases-gallery';
import { listCases } from './js/create-our-cases-gallery';
import './js/scroll';
import './js/anchor-scroll';
import { swiper } from './js/swiper';
galleryMarkup();
import './js/mobile-menu';
import './js/modals';
import './js/what-we-do';
// import './js_2/test_validation';
import './js_2/get_touch';
// import './js_2/send_contact_request';
