import './js_2/get_in_touch_with_us';
import './js/scroll';
import './js/anchor-scroll';
// import './js/create-our-cases-gallery';
// import './js/our-cases-gallery';
// import './js/swiper';
import { galleryMarkup } from './js/create-our-cases-gallery';
import { listCases } from './js/create-our-cases-gallery';
import { swiper } from './js/swiper';
galleryMarkup();
